// Copyright 2016 PlanBase Inc. & Glen Peterson
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package org.organicdesign.fp.tuple;

import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.organicdesign.testUtils.EqualsContract.equalsDistinctHashCode;
import static org.organicdesign.testUtils.EqualsContract.equalsSameHashCode;

// ======================================================================================
// THIS CLASS IS GENERATED BY /tupleGenerator/TupleGenerator.java.  DO NOT EDIT MANUALLY!
// ======================================================================================

public class Tuple2Test {
    @Test public void constructionAndAccess() {
        Tuple2<String,String> a = Tuple2.of("1st","2nd");

        assertEquals("1st", a._1());
        assertEquals("2nd", a._2());

        equalsDistinctHashCode(a, Tuple2.of("1st","2nd"),
                               Tuple2.of("1st","2nd"),
                               Tuple2.of("wrong","2nd"));


        equalsDistinctHashCode(a, Tuple2.of("1st","2nd"),
                               Tuple2.of("1st","2nd"),
                               Tuple2.of("1st","wrong"));

        equalsDistinctHashCode(Tuple2.of("1st",null),
                               Tuple2.of("1st",null),
                               Tuple2.of("1st",null),
                               Tuple2.of("1st","wrong"));

        equalsDistinctHashCode(Tuple2.of(null,"2nd"),
                               Tuple2.of(null,"2nd"),
                               Tuple2.of(null,"2nd"),
                               Tuple2.of(null,"wrong"));

        equalsSameHashCode(a, Tuple2.of("1st","2nd"),
                           Tuple2.of("1st","2nd"),
                           Tuple2.of("2nd","1st"));

        assertEquals("Tuple2(1st,2nd)", a.toString());
    }
}
